spring.application.name=republica-api

# ---------------------------------------------------------
# CONEXÃO COM O BANCO DE DADOS (POSTGRESQL NO DOCKER)
# ---------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/republica_db
spring.datasource.username=republica_user
spring.datasource.password=republica_password

# ---------------------------------------------------------
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ---------------------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------
# LOGS E CONSOLE
# ---------------------------------------------------------
spring.output.ansi.enabled=ALWAYS